#include <time.h>

typedef enum type {
    Road,
    Illumination,
    GarbageDisposal,
    PublicServices    
} IssueType;

typedef enum priority {
    High = 2,
    AboveNormal = 1,
    Normal = 0,
    BelowNormal = -1,
    Low = -2,
} IssueUrgency;

typedef enum state {
    Open,
    Ongoing,
    Closed
} IssueState;

typedef struct {
    char* id; //Is generated by taking the category and the date
    char* issuer_name;
    IssueType category;
    char* desc;
    struct tm* time; //Time and date of creation as UTC time
    IssueUrgency priority;
    IssueState state;
} Report;

Report *newReport(IssueType category, char* name, char* description);
void setReportState(Report *report, IssueState state);
void setReportUrgency(Report *report, IssueUrgency priority);
void deleteReport(Report *report);

void printReport(Report *report);